<?php $title='Reports'; $page='reports.php'; $pageScript='assets/js/reports.js';
require __DIR__.'/includes/header.php'; $u=current_user(); ?>

<div class="page-head"><h2>Report Center</h2></div>

<div class="card mb"><div class="card-pad">
  <div class="form-row3">
    <div class="field"><label>Report Type</label>
      <select id="rType">
        <option value="harvest">Harvest Report</option>
        <option value="worker">Worker Performance</option>
        <option value="section">Section Performance</option>
        <option value="expense">Expense Report</option>
        <option value="payroll">Payroll Report</option>
        <option value="profit">Profitability Report</option>
      </select></div>
    <div class="field"><label>From</label><input type="date" id="rFrom"></div>
    <div class="field"><label>To</label><input type="date" id="rTo"></div>
  </div>
  <div class="form-row3">
    <div class="field"><label>Estate</label><select id="rEstate"><option value="">All</option></select></div>
    <div class="field" id="priceWrap" style="display:none"><label>Tea Price / KG (LKR)</label><input type="number" id="rPrice" step="0.01" placeholder="e.g. 300"></div>
    <div class="field" style="display:flex;align-items:flex-end;gap:8px">
      <button class="btn" onclick="runReport()">Generate</button>
      <button class="btn gray" onclick="exportCsv()">CSV</button>
      <button class="btn gray" onclick="window.print()">Print / PDF</button>
    </div>
  </div>
</div></div>

<div class="card" id="reportCard">
  <div class="card-pad" id="reportHeader" style="display:none">
    <div style="display:flex;justify-content:space-between;align-items:center">
      <div><h3 id="rTitle" style="margin:0"></h3><small class="muted" id="rMeta"></small></div>
      <div class="muted" style="text-align:right;font-size:12px">Generated by <?=e($u['name'])?><br><?=date('Y-m-d H:i')?></div>
    </div>
  </div>
  <div class="tbl-wrap"><table class="tbl">
    <thead id="rHead"></thead>
    <tbody id="rBody"><tr><td class="empty">Select a report and click Generate</td></tr></tbody>
  </table></div>
</div>

<?php require __DIR__.'/includes/footer.php'; ?>
